### ISSUE TITLE
Scala

### ISSUE THREAD

**Issue by dcjohnson** [cptaffe/learn-scala#1]
BUT IF IT IS MORE TERSE THAN JAVA I CAN'T HAVE MY AWESOME DESIGN PATTERNS BE LONG AND MAKE ME FEEL SPECIAL.  THAT SCALA IS SHORT AND PRETTY UNLIKE AWESOME JAVA.  SCALA IS SHIT!!  THAT IS ALREADY LIKE 5 LINES LESS THAN JAVA.

**Comment by dcjohnson** [comment]
Maybe I should try Scala.

**Comment by cptaffe** [comment]
I KNOW, IT'S AWESOME. DO IT.
